version: '3'
services:
  oauth:
    build: .
    read_only: true
    restart: unless-stopped
    ports:
      - 9096:9096

  sua: 
    image: nginx:latest
    volumes:
      - ./nginx/static:/usr/share/nginx/html:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
    networks: 
      - backend
  
  db:
    image: mattermost/mattermost-prod-db
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    networks: 
      - backend

  app:
    image: mattermost/mattermost-prod-app
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
    networks: 
      - backend

  web:
    image: mattermost/mattermost-prod-web
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - backend

networks: 
  backend:
